baseURL = "https://jetechholdings.com/"
#baseURL = "https://jetech.pages.dev/"
title = "JE Tech Holdings"
theme = "congo"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  colorScheme = "slate"
  defaultAppearance = "light" # light, dark, or auto
  enableSearch = true
  
  # Homepage Configuration
  showProjectList = true # We will use this for "Services"
  projectsMax = 3

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "JE Tech Holdings"
    [languages.en.params]
      description = "Premier Security Consulting & Tech Holdings"
      # footer = "Securing Your Digital Future." 

  [languages.ko]
    languageName = "한국어"
    weight = 2
    title = "JE Tech Holdings"
    [languages.ko.params]
      description = "최고의 보안 컨설팅 및 기술 지주회사"
      # footer = "디지털 미래를 안전하게 지킵니다."

[menu]
  # English Menu
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/#services"
    weight = 10
    languages = ["en"]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 20
    languages = ["en"]

  # Korean Menu
  [[menu.main]]
    identifier = "services"
    name = "서비스"
    url = "/#services"
    weight = 10
    languages = ["ko"]
  [[menu.main]]
    identifier = "blog"
    name = "블로그"
    url = "/blog/"
    weight = 20
    languages = ["ko"]
